version: "3.8"
services:
  main:
    build:
      context: .
    environment:
      - DISPLAY=host.docker.internal:0
    hostname: spacemacs
    stdin_open: true
    tty: true
    volumes:
      - ./install-spacemacs:/home/user/install-spacemacs
      - ../.spacemacs.d:/home/user/.spacemacs.d
      - ../emacs-spacemacs:/home/user/.config/emacs
      - ../org:/home/user/org
