version: "3.8"
services:
  main:
    build:
      context: .
    environment:
      - DISPLAY=host.docker.internal:0
    hostname: doom
    stdin_open: true
    tty: true
    volumes:
      - ./install-doom-emacs:/home/user/install-doom-emacs
      - ../.doom.d:/home/user/.doom.d
      - ../emacs:/home/user/.config/emacs
      - ../org:/home/user/org
